cabinet/urls.py
from django.urls import path

from cabinet.views import (
    index,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDetailView,
    TaskDeleteView,
    WorkerCreateView,
    WorkerDetailView,
    WorkerUpdateView,
    password_change,
    TaskCompletedView,
    TaskAddOrDelWorkerView,
    WorkerListView,
    WorkerDeleteView,
    CustomLogoutView,
)

urlpatterns = [
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path(
        "task/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "task/<int:pk>/detail/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "task/<int:pk>/task_completed/",
        TaskCompletedView.as_view(),
        name="task-completed"
    ),
    path(
        "task/<int:pk>/add_or_del_worker/",
        TaskAddOrDelWorkerView.as_view(),
        name="task-add-or-del-worker"
    ),
    path(
        "worker/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "worker/<int:pk>/profile/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "worker/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "worker/community/",
        WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "worker/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path(
        "change-password/",
        password_change,
        name="change-password"
    ),
    path(
        "accounts/logout/",
        CustomLogoutView.as_view(),
        name="logout"
    ),
]


app_name = "cabinet"

it_company_task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cabinet.urls", namespace="cabinet")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cabinet/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class Position(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self) -> str:
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"
        ordering = ["username"]

    def __str__(self) -> str:
        return (
            f"{self.username} (Full name:"
            f" {self.first_name} {self.last_name} "
            f"Position: {self.position})"
        )

    def get_absolute_url(self) -> str:
        return reverse("cabinet:worker-detail", kwargs={"pk": self.pk})


class TaskType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    PRIORITY_CHOICES = (
        ("Urgent", "Urgent"),
        ("High", "High"),
        ("Normal", "Normal"),
        ("Low", "Low"),
    )

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField(default=now)
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=10, choices=PRIORITY_CHOICES, default="Normal"
    )
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(Worker, related_name="workers")

    class Meta:
        ordering = ["deadline"]

    def __str__(self) -> str:
        return self.name

cabinet/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from django.core.exceptions import ValidationError
from django.forms import DateTimeInput, NullBooleanSelect, RadioSelect
from django.utils import timezone

from cabinet.models import Task, Worker


class TaskCreateForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "deadline": DateTimeInput(attrs={"type": "datetime-local"}),
            "is_completed": NullBooleanSelect(),
            "priority": RadioSelect(),
        }

    def clean_deadline(self):
        deadline = self.cleaned_data["deadline"]
        if deadline < timezone.now():
            raise ValidationError("The date is incorrect. Date < today's date")
        return deadline


class TaskUpdateForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Task
        fields = ["description", "is_completed", "priority", "deadline", "assignees"]
        widgets = {
            "deadline": DateTimeInput(attrs={"type": "datetime-local"}),
            "is_completed": NullBooleanSelect(),
            "priority": RadioSelect(),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(TaskUpdateForm, self).__init__(*args, **kwargs)
        if not self.user_is_superuser():
            self.fields.pop("deadline")
            self.fields.pop("assignees")

    def user_is_superuser(self):
        user = self.request.user
        return user.is_superuser


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search of name task", "style": "width: 400px;"}
        ),
    )


class WorkerCreateForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "position",
            "first_name",
            "last_name",
        )


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search of username worker", "style": "width: 400px;"}
        ),
    )


class ChangePasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ["new_password1", "new_password2"]

cabinet/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LogoutView
from django.db.models import F
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from cabinet.forms import (
    TaskSearchForm,
    TaskCreateForm,
    WorkerCreateForm,
    ChangePasswordForm,
    WorkerSearchForm,
    TaskUpdateForm,
)
from cabinet.models import Task, Worker


@login_required
def index(request) -> str:
    all_task = Task.objects.all()

    not_completed_task = all_task.filter(is_completed=False)
    num_not_completed_task = not_completed_task.count()
    last_task = not_completed_task.first()

    tasks_for_user = all_task.filter(assignees=request.user.id)
    tasks_for_user_completed = tasks_for_user.filter(is_completed=True)

    context = {
        "num_not_completed_task": num_not_completed_task,
        "last_task": last_task,
        "not_completed_task": not_completed_task,
        "tasks_for_user": tasks_for_user,
        "tasks_for_user_completed": tasks_for_user_completed,
    }

    return render(request, "cabinet/index.html", context=context)


class CustomLogoutView(LogoutView):
    # Redirect to the login page after logout
    next_page = reverse_lazy("login")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "cabinet/task_list.html"
    context_object_name = "task_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TaskSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = (
            Task.objects.all()
            .select_related("task_type")
            .prefetch_related("assignees")
            .order_by(F("is_completed"), F("deadline"))
        )
        form = TaskSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskCreateForm
    success_url = reverse_lazy("cabinet:task-list")


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = (
        Task.objects.all().select_related("task_type").prefetch_related("assignees")
    )


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskUpdateForm

    def get_form_kwargs(self) -> dict:
        kwargs = super(TaskUpdateView, self).get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def get_success_url(self) -> str:
        pk = self.object.pk
        return reverse_lazy("cabinet:task-detail", kwargs={"pk": pk})


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("cabinet:task-list")


class TaskCompletedView(LoginRequiredMixin, generic.View):
    model = Task
    fields = ("is_completed",)

    def post(self, request, pk):
        task = Task.objects.get(id=pk)

        if task.is_completed is False:
            task.is_completed = True
            task.save()

        return redirect("cabinet:index")


class TaskAddOrDelWorkerView(LoginRequiredMixin, generic.View):
    model = Task
    fields = ("assignees",)

    def post(self, request, pk):
        user = request.user
        task = Task.objects.get(id=pk)

        if user in task.assignees.all():
            task.assignees.remove(user)
        else:
            task.assignees.add(user)

        url = request.environ["HTTP_REFERER"]

        return redirect(url)


def is_admin(user):
    return user.is_superuser


class WorkerCreateView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreateForm

    def test_func(self):
        return is_admin(self.request.user)


class WorkerDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("cabinet:worker-list")

    def test_func(self):
        return is_admin(self.request.user)


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.all().prefetch_related("workers__task_type")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    fields = ["username", "first_name", "last_name", "email"]

    def get_success_url(self) -> str:
        return reverse_lazy("cabinet:worker-detail", kwargs={"pk": self.object.pk})


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    template_name = "cabinet/worker_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = WorkerSearchForm(initial={"username": username})

        return context

    def get_queryset(self):
        queryset = Worker.objects.all()
        form = WorkerSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])

        return queryset


@login_required
def password_change(request) -> str:
    user = request.user
    if request.method == "POST":
        form = ChangePasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your password has been changed")
            return redirect("login")
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)
    form = ChangePasswordForm(user)
    return render(request, "cabinet/change_password.html", {"form": form})

templates/cabinet/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="content-section">
    <h2>Change Password</h2>
    <p>Please enter your new password.</p>
    <form method="POST" style="max-width: 500px;">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Change Password" class="btn btn-dark">
    </form>
  </div>
{% endblock %}

templates/cabinet/task_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="container-fluid py-4">
    <div class="col-lg-auto col-md-auto mb-md-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="d-flex justify-content-between">
            <div class="numbers">
              <h5 class="font-weight-bolder mb-0">
                {{ task.name }}
                {% if task.priority == "Urgent"  %}
                  <span class="badge badge-sm bg-danger" style="height: auto; width: auto; padding: 2px; color: white; font-size: 12px;">{{ task.priority }}</span>
                {% elif task.priority == "High" %}
                  <span class="badge badge-sm bg-warning" style="height: auto; width: auto; padding: 2px; color: white; font-size: 12px;">{{ task.priority }}</span>
                {% elif task.priority == "Normal" %}
                  <span class="badge badge-sm bg-info" style="height: auto; width: auto; padding: 2px; color: white; font-size: 12px;">{{ task.priority }}</span>
                {% elif task.priority == "Low" %}
                  <span class="badge badge-sm bg-secondary" style="height: auto; width: auto; padding: 2px; color: white; font-size: 12px;">{{ task.priority }}</span>
                {% endif %}
              </h5>
              <p class="text-sm mb-0 text-capitalize font-weight-bold">{{ task.task_type }}</p>
            </div>
            <div>
              {% if user.is_superuser %}
                <a href="{% url 'cabinet:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">
                  Delete
                </a>
              {% endif %}
              <a href="{% url 'cabinet:task-update' pk=task.id %}" class="btn btn-secondary link-to-page">
                Update
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>



    <div class="row my-4">
      <div class="col-lg-8 col-md-6 mb-md-0 mb-4">
        <div class="card">
          <div class="card-header pb-0">
            <div class="row">
              <div class="col-lg-6 col-7">
                <h3>Task Information</h3>
              </div>
            </div>
          </div>
          <div class="card-body pb-0">
            <p>{{ task.description }}</p>
            <br>
            <p><strong>Deadline: </strong>{{ task.deadline }}</p>
            <p><strong>Priority: </strong>{{ task.priority }}</p>
            <p><strong>Task type: </strong>{{ task.task_type }}</p>
            <p><strong>Total workers: </strong>{{ task.assignees.count }}</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="card h-100">
          <div class="card-header pb-0 d-flex justify-content-between">
            <h6>Who is working on the project?</h6>
            <form method="post" action="{% url 'cabinet:task-add-or-del-worker' pk=task.id %}">
                {% csrf_token %}
                {% if user in task.assignees.all %}
                  <button type="submit" class="btn btn-danger link-to-page" style="height: auto; width: auto; padding: 5px; color: white;">Del me</button>
                {% else %}
                  <button type="submit" class="btn btn-dark link-to-page" style="height: auto; width: auto; padding: 5px; color: white;">Add me</button>
                {% endif %}
              </form>
          </div>
          <div class="card-body pb-0">
            <ul>
              {% for worker in task.assignees.all %}
                <a href="{% url 'cabinet:worker-detail' pk=user.pk %}">
                  <li>
                    <strong>Full name: </strong>{{ worker.first_name }} {{ worker.last_name }}
                    <p class="text-xs text-secondary mb-0"><strong>Username: </strong>{{ worker.username }}</p>
                    <p class="text-xs text-secondary mb-0"><strong>Position: </strong>{{ worker.position }}</p>
                  </li>
                </a>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/cabinet/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate style="max-width: 800px;">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-dark">
  </form>
{% endblock %}

templates/cabinet/task_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid py-4">
  <div class="row">
    <div class="col-12">
      <div class="card mb-4">
        <div class="card-header pb-0">
          <h6 class="float-start">All Task</h6>
          <div class="float-end">
            {% block search %}
              {% include "includes/search.html" %}
            {% endblock %}
            <div class="float-end d-flex align-items-center">
              <div class="d-flex align-items-center" style="margin-right: 10px;">
                <div class="circle" style="width: 20px; height: 20px; border-radius: 50%; display: inline-block; background-color: limegreen; margin-right: 10px;"></div>
                <span class="text-xs font-weight-bold">completed</span>
              </div>
              <div class="d-flex align-items-center">
                <div class="circle" style="width: 20px; height: 20px; border-radius: 50%; display: inline-block; background-color: orange; margin-right: 10px;"></div>
                <span class="text-xs font-weight-bold">not completed</span>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body px-0 pt-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center justify-content-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Task</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Priority</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Description</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Members</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7 ps-2">Deadline</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Status</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% if task_list %}
                  {% for task in task_list %}
                    <tr>
                      <td>
                        <div class="d-flex px-2">
                          <div class="my-auto">
                            <a href="{% url 'cabinet:task-detail' pk=task.id %}">
                                <h6 class="mb-0 text-sm">{{ task.name }}</h6>
                            </a>
                            <div class="d-flex gap-2">
                              <a href="{% url "cabinet:task-detail" pk=task.id %}">
                                <p class="text-xs text-secondary mb-0">More info</p>
                              </a>
                              <a href="{% url 'cabinet:task-update' pk=task.id %}">
                                <p class="text-xs text-secondary mb-0">Update</p>
                              </a>
                            </div>
                          </div>
                        </div>
                      </td>
                      <td>
                        <div class="d-flex justify-content-center align-items-center">
                          {% if task.priority == "Urgent"  %}
                            <span class="badge badge-sm bg-danger">{{ task.priority }}</span>
                            {% elif task.priority == "High" %}
                            <span class="badge badge-sm bg-gradient-warning">{{ task.priority }}</span>
                            {% elif task.priority == "Normal" %}
                            <span class="badge badge-sm bg-gradient-info">{{ task.priority }}</span>
                            {% elif task.priority == "Low" %}
                            <span class="badge badge-sm bg-secondary">{{ task.priority }}</span>
                          {% endif %}
                        </div>
                      </td>
                      <td>
                        <p class="text-sm font-weight-bold mb-0">{{ task.description }}</p>
                      </td>
                      <td>
                        <div class="avatar-group mt-2">
                          {% if task.assignees.all %}
                            {% for assignee in task.assignees.all %}
                              {% if assignee == user %}
                                <a href="{% url 'cabinet:worker-detail' pk=assignee.id %}" class="avatar avatar-xs rounded-circle" data-bs-toggle="tooltip" data-bs-placement="bottom" title="You">
                                  <img src="{% static 'img/Profile-Avatar-you.png' %}" alt="team3">
                                </a>
                                {% else %}
                                  <a href="{% url 'cabinet:worker-detail' pk=assignee.id %}" class="avatar avatar-xs rounded-circle" data-bs-toggle="tooltip" data-bs-placement="bottom" title={{ assignee.username }}>
                                    <img src="{% static 'img/Profile-Avatar.png' %}" alt="team3">
                                  </a>
                              {% endif %}
                            {% endfor %}
                            {% else %}
                            <p>-//-</p>
                          {% endif %}
                        </div>
                        <div>
                          <form method="post" action="{% url 'cabinet:task-add-or-del-worker' pk=task.id %}">
                            {% csrf_token %}
                            {% if user in task.assignees.all %}
                              <button type="submit" class="btn btn-sm bg-gradient-faded-danger" style="height: auto; width: auto; padding: 2px; color: white;">Del me</button>
                            {% else %}
                              <button type="submit" class="btn btn-sm bg-gradient-faded-dark" style="height: auto; width: auto; padding: 2px; color: white;">Add me</button>
                            {% endif %}
                          </form>
                        </div>
                      </td>
                      <td class="align-middle text-center">
                        <span class="text-xs font-weight-bold">{{ task.deadline }}</span>
                        </td>
                      <td class="align-middle text-center">
                        {% if task.is_completed %}
                          <div class="circle" style="width: 20px; height: 20px; border-radius: 50%; display: inline-block; background-color: limegreen; margin-right: 10px;"></div>
                        {% else %}
                          <div class="circle" style="width: 20px; height: 20px; border-radius: 50%; display: inline-block; background-color: orange; margin-right: 10px;"></div>
                        {% endif %}
                        {% if user.is_superuser %}
                          <a href="{% url 'cabinet:task-delete' pk=task.id%}">
                            <span class="badge badge-sm bg-danger">DEL</span>
                          </a>
                        {% endif %}
                        </td>
                      <td class="align-middle">
                        <button class="btn btn-link text-secondary mb-0" aria-haspopup="true" aria-expanded="false">
                          <i class="fa fa-ellipsis-v text-xs"></i>
                        </button>
                      </td>
                    </tr>
                  {% endfor %}
                {% else %}
                  <tr>
                    <td colspan="4" class="text-center">
                      <p>There are no tasks yet</p>
                    </td>
                  </tr>
                {% endif %}
              </tbody>
            </table>
          </div>
          {% block pagination %}
            {% include "includes/pagination.html" %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

templates/cabinet/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid py-4">
    <div class="col-lg-auto col-md-auto mb-md-4 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="d-flex justify-content-center">
            <h1>Delete {{ worker.username }}?</h1>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-auto col-md-auto mb-md-4 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="d-flex justify-content-center">
            <form action="" method="post">
                {% csrf_token %}
              <input type="submit" value="Yes" class="btn btn-danger" width="100%">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/cabinet/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Worker</h1>
  <form action="" method="post" novalidate style="max-width: 800px;">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-dark">
  </form>
{% endblock %}

templates/cabinet/worker_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-12">
        <div class="card mb-4">
          <div class="card-header pb-0">
            <div class="d-flex justify-content-between align-items-center">
              <h6 class="float-start">Our Community</h6>
              <div>
                {% block search %}
                  {% include "includes/search.html" %}
                {% endblock %}
              </div>
            </div>
          </div>
          <div class="card-body px-0 pt-0 pb-2">
            <div class="table-responsive p-0">
              <table class="table align-items-center justify-content-center mb-0">
                <thead>
                  <tr>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Full name</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Username</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Position</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Email</th>
                  </tr>
                </thead>
                <tbody>
                  {% if worker_list %}
                    {% for worker in worker_list %}
                      <tr>
                        <td>
                          <div class="d-flex px-2">
                            <div class="my-auto">
                              <a href="{% url 'cabinet:worker-detail' pk=worker.id %}">
                                  <h6 class="mb-0 text-sm">{{ worker.first_name }} {{ worker.last_name }}</h6>
                              </a>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p class="text-sm font-weight-bold mb-0">{{ worker.username }}</p>
                        </td>
                        <td>
                          <p class="text-sm font-weight-bold mb-0">{{ worker.position }}</p>
                        </td>
                        <td>
                          <p class="text-sm font-weight-bold mb-0">{{ worker.email }}</p>
                        </td>
                        {% if user.is_superuser and user.id != worker.id %}
                        <td>
                          <a href="{% url 'cabinet:worker-delete' pk=worker.id%}">
                            <span class="badge badge-sm bg-danger">DEL</span>
                          </a>
                        </td>
                        {% endif %}
                      </tr>
                    {% endfor %}
                  {% else %}
                    <tr>
                      <td colspan="4" class="text-center">
                        <p>There are no member yet</p>
                      </td>
                    </tr>
                  {% endif %}
                </tbody>
              </table>
            </div>
            {% block pagination %}
              {% include "includes/pagination.html" %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
    {% if user.is_superuser %}
      <a class="btn btn-dark link-to-page" href="{% url 'cabinet:worker-create' %}">
        <span class="nav-link-text ms-1">Create Worker</span>
      </a>
    {% endif %}
{% endblock content %}